openapi: 3.0.0
info:
  title: Watched Show API
  version: 0.0.1
paths:
  /show/{userId}:
    get:
      summary: Returns a list of shows the user watched.
      operationId: getShows
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WatchedShow'
  /show/{userId}/{showId}:
    get:
      summary: Returns what is watched from given show
      operationId: getShow
      parameters:
        - in: path
          name: showId
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatchedShow'
  /show/{userId}/episode:
    post:
      summary: Adds a show to the watched list for the user
      operationId: addEpisode
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchedEpisodeRequest'
      responses:
        '202': # status code
          description: Accepted
components:
  schemas:
    WatchedShow:
      type: object
      properties:
        id:
          type: string
          format: uuid
        seasons:
          type: array
          items:
            $ref: '#/components/schemas/WatchedSeason'
    WatchedSeason:
      type: object
      properties:
        id:
          type: string
          format: uuid
        episodes:
          type: array
          items:
            $ref: '#/components/schemas/WatchedEpisode'
    WatchedEpisode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        episodeId:
          type: string
          format: uuid
        watchTs:
          type: string
          format: date-time

    WatchedEpisodeRequest:
      type: object
      properties:
        episodeId:
          type: string
          format: uuid
        seasonId:
          type: string
          format: uuid
        showId:
          type: string
          format: uuid
      required:
        - episodeId
        - seasonId
        - showId